### ISSUE TITLE
Use variables for all templated files

### ISSUE THREAD

**Issue by tpoindessous** [geerlingguy/ansible-role-varnish#102]
Hi

you already added a variable for default VCL `varnish_default_vcl_template_path`. 

It would be nice to have variables for all templated files, like varnish.service.j2 or varnish.params.j2

Thanks for your work !

**Comment by choukimasri** [comment]
@geerlingguy also take a look at the repo https://github.com/choukimasri/ansible-role-varnishncsa
Feel free to mod and adapt.

Best Regards.
