### ISSUE TITLE
Failed to start but no error

### ISSUE THREAD

**Issue by CashWilliams** [geerlingguy/ansible-role-varnish#12]
When called from a playbook, varnish failed to start, however no error was detected as ansible failed to detect this.

https://github.com/geerlingguy/ansible-role-varnish/blob/master/tasks/main.yml#L32

I had to login to the box and debug for a while, as `service varnish start` was just returning `fail` repeatedly. (I'm actually still not sure what the problem was.)

**Comment by geerlingguy** [comment]
Which OS was this occurring on, and with what version of Varnish? Usually this indicates a problem with the service's init script, and in Varnish's case, that init script is installed as part of the package. If the init script always returns a `0` (success), then there might not be much Ansible or this role can do...

**Comment by swoodford** [comment]
I just spent 3 hours debugging this same issue using Amazon AMI Linux.  The issue was the deprecated -w flag in DAEMON_OPTS under templates/varnish.j2, as soon as that flag was changed from 
```
-w ${VARNISH_MIN_THREADS},${VARNISH_MAX_THREADS},${VARNISH_THREAD_TIMEOUT} \
```
to
```
-p thread_pool_min=${VARNISH_MIN_THREADS} \
-p thread_pool_max=${VARNISH_MAX_THREADS} \
-p thread_pool_timeout=${VARNISH_THREAD_TIMEOUT} \
```
it was working.

Also FYI the [Ansible Galaxy role] (https://galaxy.ansible.com/detail#/role/688) has not been updated with the fixes from this GitHub repo.  That would have saved me the 3 hours if the fixes were sync'd back to Ansible Galaxy.

**Comment by geerlingguy** [comment]
@swoodford - The latest tag in Galaxy is 1.3.0, which corresponds with the same tag here (commit 0a0a5a9). There's no newer code I can send to Galaxy at this point...

**Comment by swoodford** [comment]
@geerlingguy Sorry, you are correct sir.  After some research I discovered a colleague inserted that -w flag after copying an old Varnish 3 config.  

But hopefully @CashWilliams has a similar problem which is causing the service to fail to start without a helpful error message or log output.

**Comment by geerlingguy** [comment]
@swoodford - Thanks for the update!

**Comment by geerlingguy** [comment]
So it's likely a config/VCL issue outside this role's purview—I'm going to mark this as closed, but feel free to follow up if any other issues are found!
