### ISSUE TITLE
No support for Debian 8.1 / systemd (Jessie)

### ISSUE THREAD

**Issue by scarlac** [geerlingguy/ansible-role-varnish#13]
Using `/etc/defaults/varnish` will not work for Debian 8.1 as they have switched to systemd. See this report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=749272

Support for systemd should be added somehow.

**Comment by geerlingguy** [comment]
As I'm using Varnish's own repository, this is something that needs to be fixed upstream; however, I'll leave this open in case anyone else wants to figure out a simpler fix.

**Comment by Scionar** [comment]
Pull request above added support for my enviroment.

**Comment by geerlingguy** [comment]
Fixed via above PR. Thanks!
