### ISSUE TITLE
Varnish 4.1 changes break some of the role config

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-varnish#17]
See a failed build with 4.1: https://travis-ci.org/geerlingguy/ansible-role-varnish/builds/83678271

What's new: https://www.varnish-cache.org/docs/trunk/whats-new/changes.html (no mention of the different CLI parameters though... need to dig more into it).

**Comment by olvesh** [comment]
Looks like `-u` and `-g` params to varnishd is removed. It starts with those removed.

**Comment by geerlingguy** [comment]
Fixed via #31 — thanks @olvesh and @wesnick !
