### ISSUE TITLE
Use Docker-based Travis CI tests for multi-platform support

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/ansible-role-varnish#19]
See similar: geerlingguy/ansible-role-apache#60

While setting up tests on Drupal VM https://github.com/geerlingguy/drupal-vm/pull/412, I found a few required packages that caused failures if not availsble, so I thought I'd take note of them for when you add the setup here:

- CentOS6: `logrotate`
- CentOS7: `logrotate` and `initscripts`

**Comment by geerlingguy** [comment]
Interesting... I would've thought `logrotate` was standard in minimal installs, but I guess not.

**Comment by geerlingguy** [comment]
Working on this along with a more modern set of tests for all platforms on all my roles... should be done soon!

**Comment by geerlingguy** [comment]
This was already done some time ago, and I just added a commit to make it even more svelte.
