### ISSUE TITLE
Varnish can't listen on 80 port

### ISSUE THREAD

**Issue by zx1986** [geerlingguy/ansible-role-varnish#49]
I ran into this problem:
http://www.varnish-cache.org/docs/trunk/tutorial/putting_varnish_on_port_80.html

But I can't fix with that blog post.
It seems need a patch to this role.

OS: Ubuntu Server 16.04 LTS x86_64

**Comment by zx1986** [comment]
And I follow this to fix it by manual:
http://www.varnish-cache.org/docs/trunk/tutorial/putting_varnish_on_port_80.html

**Comment by geerlingguy** [comment]
@zx1986 - Does the `varnish_listen_port` config not work for you? If I set it to `80` or `81` or some other port, it works for me. Are you certain there's not another service running on your server that's trying to take over 80?

**Comment by zx1986** [comment]
@geerlingguy I had config `varnish_listen_port` to another port, 
my Apache is on 8080 port with another role (your Apache role actually :-) 

The very first time I play on machine, then check `netstat -lnt`, there were only:
```
8080 listen
22 listen 
```

No 80 port (the `varnish_listen_port`).

**Comment by geerlingguy** [comment]
@zx1986 - I'll have to do some more testing locally—I'm normally running Varnish on `81`, and either nginx, pound, or apache on `80`, so I haven't tried `80` specifically.

Can you try setting that to `81` and running your playbook, and see if at least port 81 works correctly?

**Comment by zx1986** [comment]
@geerlingguy ok, I will find a chance to test it & report.

**Comment by TipiT** [comment]
It works at least on Ubuntu 16.04-
Also works if one adds: varnish_listen_port: "8000,PROXY" to enable the PROXY support.

**Comment by zx1986** [comment]
Sorry, I got few projects deadline on recently, I will try again later.

**Comment by davidak** [comment]
I have the same problem on Ubuntu 16.04.

```
cat /lib/systemd/system/varnish.service
[Unit]
Description=Varnish HTTP accelerator
Documentation=https://www.varnish-cache.org/docs/4.1/ man:varnishd

[Service]
Type=simple
LimitNOFILE=131072
LimitMEMLOCK=82000
ExecStart=/usr/sbin/varnishd -j unix,user=vcache -F -a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m
ExecReload=/usr/share/varnish/reload-vcl
ProtectSystem=full
ProtectHome=true
PrivateTmp=true
PrivateDevices=true

[Install]
WantedBy=multi-user.target
```

```
cat /etc/systemd/system/varnish.service
[Unit]
Description=Varnish Cache, a high-performance HTTP accelerator

[Service]
Type=forking
PIDFile=/run/varnishd.pid
LimitNOFILE=131072
LimitMEMLOCK=82000
ExecStart=/usr/sbin/varnishd -a :80 -T 127.0.0.1:6082 -P /run/varnishd.pid -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,3160M
ExecReload=/usr/share/varnish/reload-vcl

[Install]
WantedBy=multi-user.target
```

```
less /etc/default/varnish
...
DAEMON_OPTS="-a :80 \
             -T localhost:6082 \
             -f /etc/varnish/default.vcl \
             -S /etc/varnish/secret \
             -s malloc,256m"
```

```
systemctl status varnish.service
● varnish.service - Varnish HTTP accelerator
   Loaded: loaded (/lib/systemd/system/varnish.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2017-03-20 13:26:55 CET; 4s ago
     Docs: https://www.varnish-cache.org/docs/4.1/
           man:varnishd
  Process: 13196 ExecReload=/usr/share/varnish/reload-vcl (code=exited, status=0/SUCCESS)
 Main PID: 14073 (varnishd)
   CGroup: /system.slice/varnish.service
           ├─14073 /usr/sbin/varnishd -j unix,user=vcache -F -a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m
           └─14086 /usr/sbin/varnishd -j unix,user=vcache -F -a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m
```

systemd seams to only use `/lib/systemd/system/varnish.service`.

**Comment by davidak** [comment]
The `/etc/systemd/system/varnish.service` is used after i manually executed `systemctl daemon-reload`.

I changed the port again and rolled out Ansible and now it works directly. very strange.

This role should actually reload the systemd config itself: https://github.com/geerlingguy/ansible-role-varnish/blob/master/tasks/main.yml#L33

**Comment by zx1986** [comment]
@davidak Have you try this?
http://www.varnish-cache.org/docs/trunk/tutorial/putting_varnish_on_port_80.html#debian-v8-ubuntu-v15-04

**Comment by davidak** [comment]
@zx1986 yes, like you see in my previous comment.

**Comment by flailingmaster** [comment]
I had similar trouble.  I found that Apache was listening on 81, but Varnish was listening on 6081 by running:
`# netstat -tulnp`

I also found that /etc/systemd/system/varnish.service existed and appeared to exist and be set correctly to listen on port 80. The following appeared to fix it:

`#  /etc/init.d/varnish stop`
`# systemctl daemon-reload`
`# /etc/init.d/varnish start`

There may have been some other floundering, but I think that did it.

**Comment by geerlingguy** [comment]
@flailingmaster - Thanks for the confirmation. I wonder if there's something else I can do in this role to make sure that the settings take effect immediately. It seems that the settings are correct, but they will only work after systemd reloads the varnish service, or after a full server reboot. Not ideal, but at least there's a workaround.

**Comment by geerlingguy** [comment]
This should be working on all supported OSes at this point—I think one of Ansible's recent updates fixed the way service reloads work with systemd-powered distributions.

I've also fixed a quirk that was only applying settings correctly on Debian 8 (not 9+) and Ubuntu 16.04 (not 17+), over in #66. So going to mark this as closed!
