### ISSUE TITLE
ansible won't copy custom default.vcl.js

### ISSUE THREAD

**Issue by johnscancella** [geerlingguy/ansible-role-varnish#56]
no matter what I seem to do, ansible won't copy my custom default.vcl.js file
My ansible playbook and custom default.vcl is included (just remove .txt).

[default.vcl.j2.txt](https://github.com/geerlingguy/ansible-role-varnish/files/1039313/default.vcl.j2.txt)
[varnish.yml.txt](https://github.com/geerlingguy/ansible-role-varnish/files/1039316/varnish.yml.txt)

**Comment by geerlingguy** [comment]
@johnscancella - You need to set the `varnish_default_vcl_template_path` variable to the relative path (from your playbook) to the default VCL (see vars in https://github.com/geerlingguy/ansible-role-varnish#role-variables).

Please let me know if that works for you.

**Comment by johnscancella** [comment]
@geerlingguy I did that and it still doesn't work. I just end up getting your default template

**Comment by geerlingguy** [comment]
Can you verify what version of the varnish role is currently installed (that you're using)?

**Comment by johnscancella** [comment]
version 1.9.0
