### ISSUE TITLE
make TTL configurable

### ISSUE THREAD

**Issue by johnscancella** [geerlingguy/ansible-role-varnish#62]
Could you make it so that the TTL is configurable and not just 120 seconds?

**Comment by geerlingguy** [comment]
That sounds like a good idea. Note that I _think_ you can already override it per backend, if you want (see https://github.com/geerlingguy/ansible-role-varnish/blob/b7dd45abac7aadf409d5414e1b9be407022af21f/templates/varnish.params.j2#L28).
