### ISSUE TITLE
Failed starting varnish

### ISSUE THREAD

**Issue by ddepaoli3** [geerlingguy/ansible-role-varnish#63]
Using the role with an Amazon Linux AMI I get this error;

_TASK [ansible-role-varnish : Ensure Varnish services are started enabled on startup.] ******************************************************************************************************************************************************************************************
failed: [172.20.30.251] (item=varnish) => {"failed": true, "item": "varnish", "msg": "Starting Varnish Cache: [FAILED]\r\n"}_ 

Trying to start and stop the service manually I get:
_Stopping Varnish Cache:                                    [FAILED]
Starting Varnish Cache:                                    [FAILED]_

In my configuration I use Varnish 4.1

**Comment by ddepaoli3** [comment]
The commit that broke the role is c38f710348a18f630c661d063bfb51104526ed49. I suppose it was the chenge in repository. I'll investigate about it

**Comment by geerlingguy** [comment]
@ddepaoli3 - Yeah, I haven't been testing this role on Amazon Linux, so I'm wondering if there might be an issue with the newer Varnish yum repos and the current version of Amazon Linux. You might want to inquire over in the Varnish package GitHub issues: https://github.com/varnishcache/pkg-varnish-cache/issues
