### ISSUE TITLE
Ubuntu 16.04 is not enabling at boot

### ISSUE THREAD

**Issue by andrewhowdencom** [geerlingguy/ansible-role-varnish#64]
Stub issue. I'm looking at this now, and will write what I find here for future people.

**Comment by andrewhowdencom** [comment]
There is both a systemd service unit and a sysvinit bash script. I think ansible might be enabling the bash script somehow, by precedence.

**Comment by andrewhowdencom** [comment]
Moving the sysvinit script out the way means the systemd service is enabled on boot. Just gonna try it the other way

**Comment by andrewhowdencom** [comment]
Perhaps related: https://github.com/ansible/ansible/issues/22303

**Comment by andrewhowdencom** [comment]
Potential workaround: https://github.com/ansible/ansible-modules-core/issues/3764#issuecomment-284331673

**Comment by andrewhowdencom** [comment]
Might be resolved by https://github.com/geerlingguy/ansible-role-varnish/pull/65. Just testing.

**Comment by andrewhowdencom** [comment]
Yah it worked. Using our fork for now -- if this gets merged in, awesome. <3

**Comment by geerlingguy** [comment]
Thanks for the PR! I left a couple review notes.

**Comment by andrewhowdencom** [comment]
Hola! Thanks for getting back to me. I've amended the review, and am running a test build now as a sanity check (though I have used this syntax previously). 

As a design note, would you consider adding a `.yamllint` file to the top of your repo? This would make code style nits such as EOL easier to catch in future

**Comment by andrewhowdencom** [comment]
Booted fine

**Comment by geerlingguy** [comment]
This is fixed via the merged PR now. Thanks!
