### ISSUE TITLE
Debian 9: varnish.service file defaults used instead of /etc/defaults/varnish

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-varnish#66]
At least in my Docker container build: https://github.com/geerlingguy/drupal-vm/issues/1451#issuecomment-320837119

Because of this, on a fresh Debian 9 installation of Varnish, the role's configuration for ports (and some other things) have no effect on the running instance of Varnish!

**Comment by geerlingguy** [comment]
This build both proves that port 80 seems to work in all the other distros, and that this bug exists only (currently) for Debian 9...

https://travis-ci.org/geerlingguy/ansible-role-varnish/builds/262084831

**Comment by denics** [comment]
I do not know if this should be closed, we still have the same issue with Debian 10.
The role write /etc/default/varnish, but then Debian starts varnish using its own systemd service.
