### ISSUE TITLE
Utopic Unicorn Fails To Install

### ISSUE THREAD

**Issue by conatus** [geerlingguy/ansible-role-varnish#7]
The Varnish apt repositories lack builds for Utopic Unicorn,  Ubuntu 14.10, so after obtaining the key the build of the box fails.

I fixed this locally by simply installing the version of Varnish 4.0 that is in the Ubuntu repositories. 

Should I do this programmatically and submit a PR?

**Comment by geerlingguy** [comment]
@conatus - I generally only support LTS releases of Ubuntu, as the non-LTS versions often don't have official support from upstream PPAs (and in this case, I don't think Varnish's PPA has a package for 14.10).

If this is incorrect, please let me know and we can reopen and discuss further...
