### ISSUE TITLE
Fail to rotate logs for varnishncsa

### ISSUE THREAD

**Issue by xlr-8** [geerlingguy/ansible-role-varnish#74]
When installing the role on Debian Jessie, the logrotation seems to have a bug:
The cron complains of the following issue:
```bash
/etc/cron.daily/logrotate:
error: error running non-shared postrotate script for /var/log/varnish/varnishncsa.log of '/var/log/varnish/varnishncsa.log '
run-parts: /etc/cron.daily/logrotate exited with return code 1
```

When looking at the configuration, it looks like invoke.rc has some issue with restarting the varnishncsa service. By updating it simply with:
```bash
/var/log/varnish/varnishncsa.log {
  daily
  rotate 7
  compress
  delaycompress
  missingok
  postrotate
    if [ -d /run/systemd/system ]; then
       systemctl -q is-active varnishncsa.service || exit 0
    fi
-    /usr/sbin/invoke-rc.d varnishncsa reload > /dev/null
+    systemctl reload varnishncsa.service > /dev/null
  endscript
}
```

Seem to solve this issue. Is it something you already encounter?

**Comment by talset** [comment]
I have the same issue. Any chance to have a look on it ?

Thanks !
