### ISSUE TITLE
Can not add repository (DrupalVM, vagrant_box: geerlingguy/ubuntu1804)

### ISSUE THREAD

**Issue by homeandr777** [geerlingguy/ansible-role-varnish#77]
TASK [geerlingguy.varnish : include_tasks] *************************************
skipping: [drupalvm]

TASK [geerlingguy.varnish : include_tasks] *************************************
included: /vagrant/provisioning/roles/geerlingguy.varnish/tasks/setup-Debian.yml for drupalvm

TASK [geerlingguy.varnish : Ensure APT HTTPS Transport is installed.] **********
changed: [drupalvm]

TASK [geerlingguy.varnish : Add packagecloud.io Varnish apt key.] **************
changed: [drupalvm]

TASK [geerlingguy.varnish : Add packagecloud.io Varnish apt repository.] *******
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt.cache.FetchFailedException: E:The repository 'https://packagecloud.io/varnishcache/varnish51/ubuntu bionic Release' does not have a Release file.
fatal: [drupalvm]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_ARMCpS/ansible_module_apt_repository.py\", line 551, in <module>\n    main()\n  File \"/tmp/ansible_ARMCpS/ansible_module_apt_repository.py\", line 543, in main\n    cache.update()\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 505, in update\n    raise FetchFailedException(e)\napt.cache.FetchFailedException: E:The repository 'https://packagecloud.io/varnishcache/varnish51/ubuntu bionic Release' does not have a Release file.\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

**Comment by chumkui** [comment]
I had exactly this error. I rebooted the box, re run the script and all worked OK

**Comment by geerlingguy** [comment]
I'm guessing it was a temporary network issue... it happens sometimes, and usually clears up after a few minutes (or in @chumkui's case, a reboot!). Going to close the issue; please reopen if you can reproduce the error again.
