### ISSUE TITLE
page-185-198 Ansible for DevOps

### ISSUE THREAD

**Issue by sridharan123456** [geerlingguy/ansible-role-varnish#81]
Following what you have outlined in your book 

[root@ansible1 lamp-infrastructure]# tree
.
├── configure.yml
├── index.php.j2
├── inventories
├── playbooks
│   ├── db
│   │   ├── main.yml
│   │   └── vars.yml
│   ├── memcached
│   │   ├── main.yml
│   │   └── vars.yml
│   ├── varnish
│   │   ├── main.yml
│   │   ├── templates
│   │   │   └── default.vcl.j2
│   │   └── vars.yml
│   └── www
│       ├── index.php.j2
│       ├── main.yml
│       └── vars.yml
├── provisioners
├── provision.yml
└── Vagrantfile
9 directories, 13 files
[root@ansible1 lamp-infrastructure]# ansible-playbook configure.yml 
ERROR! variable files must contain either a dictionary of variables, or a list of dictionaries. Got: firewall_all
owed_tcp_ports - "22" - "80" (<class 'ansible.parsing.yaml.objects.AnsibleUnicode'>)
[root@ansible1 lamp-infrastructure]#

Testing from Google Cloud Compute instance  - ansinble1

**Comment by geerlingguy** [comment]
@sridharan123456 have you tried using the example straight from the GitHub repository? https://github.com/geerlingguy/ansible-for-devops/tree/master/lamp-infrastructure

I'm guessing the formatting for the allowed tcp ports might be incorrect in your files?

```yaml
firewall_allowed_tcp_ports:
  - 22
  - 80
```

That's how it should look.

**Comment by sridharan123456** [comment]
firewall_allowed_tcp_ports:
  - 22
  - 80 

I have given with - "22" and - "80" as per the book.

Let me chek this - firewall_allowed_tcp_ports:
  - 22
  - 80

Let me check the github repository.

Thanks
Sri
