### ISSUE TITLE
Varnish doesn't have package for Ubuntu 20.04 Focal Fossa

### ISSUE THREAD

**Issue by 7php** [geerlingguy/ansible-role-varnish#95]
Hi, I am not able to get this to install on Ubuntu 20.04
Below error:

```
Ign:5 https://packagecloud.io/varnishcache/varnish64/ubuntu focal InRelease
Err:6 https://packagecloud.io/varnishcache/varnish64/ubuntu focal Release
  404  Not Found [IP: 2600:1f1c:2e5:6900:4e24:4dad:908b:18c6 443]
Reading package lists... Done
E: The repository 'https://packagecloud.io/varnishcache/varnish64/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by geerlingguy** [comment]
@7php - Varnish doesn't yet have a published package for Focal Fossa: https://packagecloud.io/varnishcache/varnish64

It looks like there's an older Varnish version available in Focal's main apt repo: https://launchpad.net/ubuntu/focal/+package/varnish (6.2), but I would rather just wait for the packaging system to update with focal support.

**Comment by 7php** [comment]
yes it seems the 6.2 is among the package that has a serious bug.
Hence wanted to get the latest 6.4

Do you think it would take long before 6.4 lands for ubuntu 20.04?

**Comment by geerlingguy** [comment]
@7php - I think we can leave this open for now. I added an upstream issue to see if we can get focal supported on packagecloud: https://github.com/varnishcache/pkg-varnish-cache/issues/139

**Comment by 7php** [comment]
ok perfect, thank you very much @geerlingguy

**Comment by 7php** [comment]
Adding this reference:
#https://github.com/varnishcache/varnish-cache/pull/3263

**Comment by 7php** [comment]
More reference:
#https://github.com/varnishcache/varnish-cache/pull/3313

**Comment by geerlingguy** [comment]
It looks like the code to build the Focal package was merged, but a package for Focal still doesn't exist—yet.

**Comment by 7php** [comment]
indeed.. I have asked them when we can expect that to happen.. let's see

**Comment by andy-chiu-conrad** [comment]
May I ask if there are any news on this?

**Comment by geerlingguy** [comment]
It looks like there's a 'weekly' build now: https://packagecloud.io/varnishcache/varnish-weekly — but none in a versioned release :-/

**Comment by moismailzai** [comment]
> > It looks like there's a 'weekly' build now: https://packagecloud.io/varnishcache/varnish-weekly — but none in a versioned release :-/
> 
> Can we use the existing variables to point to the ` varnishcache / varnish-weekly / ubuntu / focal / varnish-dev_20200803-weekly~focal-1_amd64.deb`?
> 
> Thank you,
> R

As a temporary workaround you can override the `varnish_packagecloud_repo` variable in the role:

```
tasks:
- include_role:
    name: "geerlingguy.varnish"
  vars:
    varnish_packagecloud_repo: "varnish-weekly"
```

**Comment by Krapulat** [comment]
Any news?

**Comment by andy-chiu-conrad** [comment]
Will there be a stable release soon here https://packagecloud.io/varnishcache/varnish64, not the weekly release? 

The weekly release is fine for our testing environments ... but for production we will need a stable version. Thx
