### ISSUE TITLE
Listen protocol not configurable

### ISSUE THREAD

**Issue by fhebert-ehess** [geerlingguy/ansible-role-varnish#98]
It would be great to be able to specify the listening protocol of varnishd (-a switch). 

A new variable would be necessary : varnish_listen_protocol and the ExecStart line of systemd service would be modified as :

varnish.service.j2 : 
ExecStart=/usr/sbin/varnishd -a {{ varnish_listen_address }}:{{ varnish_listen_port }},{{ varnish_listen_protocol }} -T {{ varnish_admin_listen_host }}:{{ varnish_admin_listen_port }}{% if varnish_pidfile %} -P {{ varnish_pidfile }}{% endif %} -f {{ varnish_config_path }}/default.vcl -S {{ varnish_config_path }}/secret -s {{ varnish_storage }} {{ varnishd_extra_options }}

Also in varnish.params.j2 : a new option : 
VARNISH_LISTEN_PROTOCOL={{ varnish_listen_protocol }}

**Comment by Bilge** [comment]
This is still not sufficient. Look at the [documentation for `-a`](https://varnish-cache.org/docs/6.5/reference/varnishd.html) and you can see there are far more options available, including *user*, *group*, and *mode*. Moreover, Unix domain sockets can be used, which don't specify address *or* port. But more importantly, **-a can be specified multiple times** and this role has absolutely no provision for that facility. The current implementation is incredibly short-sighted.
